window.products = [
{slug:"coffee-body-scrub-soap",name:"Coffee Body Scrub Soap",tagline:"Coffee-infused body care",description:"A coffee-infused soap made from coconut soap that cleanses, gently exfoliates dead skin cells, and leaves the body soft and refreshed with a warm coffee scent.",images:["images/products/Coffee Body Scrub Soap/Coffee Body Scrub Soap 1.png","images/products/Coffee Body Scrub Soap/Coffee Body Scrub Soap 2.png"]},
{slug:"coffee-loofah-scrub-soap-1",name:"Coffee Loofah Scrub Soap",tagline:"Coffee & loofah exfoliation",description:"An exfoliating body soap made from coconut soap and infused with coffee and natural loofah to cleanse the skin, gently remove dead skin cells, and leave the body feeling soft, smooth, and refreshed with a warm coffee scent.",images:["images/products/Coffee Loofah Scrub Soap 1/Coffee Loofah Scrub Soap 1 (1).png","images/products/Coffee Loofah Scrub Soap 1/Coffee Loofah Scrub Soap 2.png"]},
{slug:"coffee-loofah-scrub-soap-2",name:"Coffee Loofah Scrub Soap",tagline:"Coffee & loofah exfoliation",description:"A body soap made from coconut soap infused with coffee and natural loofah for effective exfoliation. It removes dead skin cells and impurities, leaving the skin soft, polished, and refreshed with a warm coffee scent.",images:["images/products/Coffee Loofah Scrub Soap 2/Coffee Loofah Scrub Soap 1.png","images/products/Coffee Loofah Scrub Soap 2/Coffee Loofah Scrub Soap 2.png"]},
{slug:"coffee-loofah-scrub-soap-3",name:"Coffee Loofah Scrub Soap",tagline:"Coffee & loofah exfoliation",description:"A body soap made from coconut soap and infused with coffee and natural loofah for effective exfoliation. It removes dead skin cells and impurities, leaving the skin soft, smooth, and refreshed with a warm coffee scent.",images:["images/products/Coffee Loofah Scrub Soap 3/Coffee Loofah Scrub Soap 1.png","images/products/Coffee Loofah Scrub Soap 3/Coffee Loofah Scrub Soap 2.png"]},
{slug:"coffee-massage-scrub-soap",name:"Coffee Massage Scrub Soap",tagline:"Coffee & massage beads",description:"A massage soap made from coconut soap and infused with coffee, featuring massage beads that cleanse, exfoliate dead skin cells, and leave the body smooth, refreshed, and delicately scented.",images:["images/products/Coffee Massage Scrub Soap/Coffee Massage Scrub Soap 1.png","images/products/Coffee Massage Scrub Soap/Coffee Massage Scrub Soap 2.png"]},
{slug:"crystal-rose-body-scrub-soap",name:"Crystal Rose Body Scrub Soap",tagline:"Damask rose & almond oil",description:"A coconut soap enriched with almond oil and Damask rose petals that gently cleanses and leaves the skin soft, smooth, refreshed, and delicately scented with roses.",images:["images/products/Crystal Rose Body Scrub Soap/Crystal Rose Body Scrub Soap 1.png","images/products/Crystal Rose Body Scrub Soap/Crystal Rose Body Scrub Soap 2.png"]},
{slug:"layered-rose-chia-body-scrub-soap",name:"Layered Rose & Chia Body Scrub Soap",tagline:"Rose petals & chia seeds",description:"A dual-layer soap made from coconut soap and enriched with almond oil, Damask rose petals, and chia seeds. It gently cleanses and exfoliates, leaving the skin soft, smooth, and delicately scented with roses.",images:["images/products/Layered Rose & Chia Body Scrub Soap/Layered Rose & Chia Body Scrub Soap 1.png","images/products/Layered Rose & Chia Body Scrub Soap/Layered Rose & Chia Body Scrub Soap 2.png"]},
{slug:"milky-body-mist",name:"Milky Body Mist",tagline:"Nourish • Protect • Glow",description:"Refresh your skin with our Milky Body Mist, designed to leave your body beautifully scented and refreshed. Its milky formula gives your skin a soft touch, while the long-lasting fragrance stays with you throughout the day.",scents:["Jasmine Milk Powder","Velvet Choco Vanile","Midnight","Vanilla Cashmere"],images:["images/products/Milky Body Mist/Milky Body Mist 1.png","images/products/Milky Body Mist/Milky Body Mist 2.png","images/products/Milky Body Mist/Milky Body Mist 3.png"]},
{slug:"milky-hair-mist",name:"Milky Hair Mist",tagline:"Vitamin shine & smooth feel",description:"Refresh your hair with our Milky Hair Mist, designed to leave it feeling soft, fresh, and beautifully scented. Its formula adds a touch of shine, with a soft, long-lasting fragrance that gently lingers on your hair.",scents:["Honey Suckle","Cherry Blossom","Berry","Choco Vanile"],images:["images/products/Milky Hair Mist/Milky Hair Mist 1.png","images/products/Milky Hair Mist/Milky Hair Mist 2.png","images/products/Milky Hair Mist/Milky Hair Mist 3.png"]},
{slug:"rose-body-scrub-soap",name:"Rose Body Scrub Soap",tagline:"Damask rose & almond oil",description:"A coconut soap enriched with almond oil and Damask rose petals that gently cleanses and leaves the skin soft, smooth, refreshed, and delicately scented with roses.",images:["images/products/Rose Body Scrub Soap/Rose Body Scrub Soap 1.png","images/products/Rose Body Scrub Soap/Rose Body Scrub Soap 2.png"]},
{slug:"shea-body-butter",name:"Shea Body Butter",tagline:"Deep moisture & soft skin",description:"Indulge your skin in rich, creamy moisture with our Shea Body Butter. Made with pure shea butter and cocoa butter to deeply nourish, hydrate, and leave your skin soft and smooth. Finished with a soft, long-lasting scent that gently lingers on the skin.",images:["images/products/Shea Body Butter/Shea Body Butter 1.png","images/products/Shea Body Butter/Shea Body Butter 2.png","images/products/Shea Body Butter/Shea Body Butter 3.png"]},
{slug:"solid-perfume",name:"Solid Perfume",tagline:"Balm-based, portable luxury",description:"A smooth, creamy Solid Perfume that melts gently onto the skin, leaving a beautiful long-lasting fragrance. Perfect for applying to pulse points whenever you want a fresh touch of your favorite scent.",images:["images/products/Solid Perfume/Solid Perfume 1.png","images/products/Solid Perfume/Solid Perfume 2.png","images/products/Solid Perfume/Solid Perfume 3.png"]}
];

